# Generated by Django 2.1.4 on 2018-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='picture',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='isFavorite',
            field=models.BooleanField(default=True),
        ),
    ]
