# Generated by Django 2.1.4 on 2018-12-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes_site', '0003_auto_20181204_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='updated_at',
        ),
    ]
